import java.time.LocalDate;

public class Main {
    public static void main(String[] args) {
        MusicPlayer player = new MusicPlayer();

        player.addSong("Numb", "Linkin Park");
        player.addSong("In the End", "Linkin Park");
        player.addSong("Bohemian Rhapsody", "Queen");
        player.addSong("Stairway to Heaven", "Led Zeppelin");
        player.addSong("Hotel California", "Eagles");
        player.addSong("Hey Jude", "The Beatles");
        player.addSong("Shape of You", "Ed Sheeran");
        player.addSong("Blinding Lights", "The Weeknd");
        player.addSong("Someone Like You", "Adele");
        player.addSong("Rolling in the Deep", "Adele");
        player.addSong("Smells Like Teen Spirit", "Nirvana");
        player.addSong("Sweet Child O' Mine", "Guns N' Roses");
        player.addSong("Wonderwall", "Oasis");
        player.addSong("Yesterday", "The Beatles");
        player.addSong("Let It Be", "The Beatles");
        player.addSong("Thunderstruck", "AC/DC");
        player.addSong("Back in Black", "AC/DC");
        player.addSong("Livin' on a Prayer", "Bon Jovi");
        player.addSong("Billie Jean", "Michael Jackson");
        player.addSong("Thriller", "Michael Jackson");
        player.addSong("Uptown Funk", "Mark Ronson ft. Bruno Mars");
        player.addSong("All of Me", "John Legend");
        player.addSong("Perfect", "Ed Sheeran");
        player.addSong("Bad Guy", "Billie Eilish");
        player.addSong("Old Town Road", "Lil Nas X");
        player.addSong("Shake It Off", "Taylor Swift");
        player.addSong("Blank Space", "Taylor Swift");
        player.addSong("Rockstar", "Post Malone");
        player.addSong("Circles", "Post Malone");
        player.addSong("Sunflower", "Post Malone ft. Swae Lee");
        player.addSong("Levitating", "Dua Lipa ft. DaBaby");
        player.addSong("Don't Start Now", "Dua Lipa");
        player.addSong("Closer", "The Chainsmokers ft. Halsey");
        player.addSong("Memories", "Maroon 5");
        player.addSong("Sugar", "Maroon 5");
        player.addSong("Moves Like Jagger", "Maroon 5 ft. Christina Aguilera");
        player.addSong("Senorita", "Shawn Mendes ft. Camila Cabello");
        player.addSong("Havana", "Camila Cabello");
        player.addSong("Despacito", "Luis Fonsi ft. Daddy Yankee");
        player.addSong("Shallow", "Lady Gaga & Bradley Cooper");
        player.addSong("Take Me to Church", "Hozier");
        player.addSong("Counting Stars", "OneRepublic");
        player.addSong("Apologize", "Timbaland ft. OneRepublic");
        player.addSong("Demons", "Imagine Dragons");
        player.addSong("Radioactive", "Imagine Dragons");
        player.addSong("Believer", "Imagine Dragons");
        player.addSong("Wake Me Up", "Avicii");
        player.addSong("Levels", "Avicii");
        player.addSong("I Gotta Feeling", "The Black Eyed Peas");


        player.playSong("Numb");
        player.playSong("In the End");
        player.playSong("Bohemian Rhapsody");
        player.playSong("Stairway to Heaven");
        player.playSong("Hotel California");
        player.playSong("Hey Jude");
        player.playSong("Shape of You");
        player.playSong("Blinding Lights");
        player.playSong("Someone Like You");
        player.playSong("Rolling in the Deep");
        player.playSong("Smells Like Teen Spirit");
        player.playSong("Sweet Child O' Mine");
        player.playSong("Wonderwall");
        player.playSong("Yesterday");
        player.playSong("Let It Be");
        player.playSong("Thunderstruck");
        player.playSong("Back in Black");
        player.playSong("Livin' on a Prayer");
        player.playSong("Billie Jean");
        player.playSong("Thriller");
        player.playSong("Uptown Funk");
        player.playSong("All of Me");
        player.playSong("Perfect");
        player.playSong("Bad Guy");
        player.playSong("Old Town Road");
        player.playSong("Shake It Off");
        player.playSong("Blank Space");
        player.playSong("Rockstar");
        player.playSong("Circles");
        player.playSong("Sunflower");
        player.playSong("Levitating");
        player.playSong("Don't Start Now");
        player.playSong("Closer");
        player.playSong("Memories");
        player.playSong("Sugar");
        player.playSong("Moves Like Jagger");
        player.playSong("Senorita");
        player.playSong("Havana");
        player.playSong("Despacito");
        player.playSong("Shallow");
        player.playSong("Take Me to Church");
        player.playSong("Counting Stars");
        player.playSong("Apologize");
        player.playSong("Demons");
        player.playSong("Radioactive");
        player.playSong("Believer");
        player.playSong("Wake Me Up");
        player.playSong("Levels");
        player.playSong("I Gotta Feeling");
        player.playSong("Bohemian Rhapsody");
        player.playSong("In the End");
        player.playSong("Blinding Lights");
        player.playSong("Numb");
        player.playSong("Shape of You");
        player.playSong("Rolling in the Deep");
        player.playSong("Sweet Child O' Mine");
        player.playSong("Hotel California");
        player.playSong("Someone Like You");
        player.playSong("Hey Jude");
        player.playSong("Thunderstruck");
        player.playSong("Thriller");
        player.playSong("Livin' on a Prayer");
        player.playSong("Back in Black");
        player.playSong("Uptown Funk");
        player.playSong("Memories");
        player.playSong("Perfect");
        player.playSong("Senorita");
        player.playSong("Blank Space");
        player.playSong("Believer");
        player.playSong("Don't Start Now");
        player.playSong("Wake Me Up");
        player.playSong("Levitating");
        player.playSong("Circles");
        player.playSong("Moves Like Jagger");
        player.playSong("Closer");
        player.playSong("Counting Stars");
        player.playSong("Shallow");
        player.playSong("Despacito");
        player.playSong("Take Me to Church");
        player.playSong("Havana");
        player.playSong("Old Town Road");
        player.playSong("Bad Guy");
        player.playSong("Demons");
        player.playSong("Sugar");
        player.playSong("I Gotta Feeling");
        player.playSong("Radioactive");
        player.playSong("All of Me");
        player.playSong("Smells Like Teen Spirit");
        player.playSong("Sunflower");
        player.playSong("Let It Be");
        player.playSong("Yesterday");
        player.playSong("Bohemian Rhapsody");
        player.playSong("In the End");
        player.playSong("Billie Jean");
        player.playSong("Blinding Lights");
        player.playSong("Rolling in the Deep");
        player.playSong("Someone Like You");
        player.playSong("Hey Jude");
        player.playSong("Numb");
        player.playSong("Shape of You");
        player.playSong("Hotel California");
        player.playSong("Sweet Child O' Mine");
        player.playSong("Thunderstruck");
        player.playSong("Thriller");
        player.playSong("Back in Black");
        player.playSong("Livin' on a Prayer");
        player.playSong("Memories");
        player.playSong("Perfect");
        player.playSong("Uptown Funk");
        player.playSong("Senorita");
        player.playSong("Blank Space");
        player.playSong("Believer");
        player.playSong("Don't Start Now");
        player.playSong("Wake Me Up");
        player.playSong("Levitating");
        player.playSong("Circles");
        player.playSong("Moves Like Jagger");
        player.playSong("Closer");
        player.playSong("Counting Stars");
        player.playSong("Shallow");
        player.playSong("Despacito");
        player.playSong("Take Me to Church");
        player.playSong("Havana");
        player.playSong("Old Town Road");
        player.playSong("Bad Guy");
        player.playSong("Demons");
        player.playSong("Sugar");
        player.playSong("I Gotta Feeling");
        player.playSong("Radioactive");
        player.playSong("All of Me");
        player.playSong("Smells Like Teen Spirit");
        player.playSong("Sunflower");
        player.playSong("Let It Be");
        player.playSong("Yesterday");
        player.playSong("Hotel California");
        player.playSong("Someone Like You");
        player.playSong("Numb");
        player.playSong("Shape of You");
        player.playSong("Rolling in the Deep");
        player.playSong("Sweet Child O' Mine");
        player.playSong("Blinding Lights");
        player.playSong("Memories");
        player.playSong("Perfect");
        player.playSong("Uptown Funk");
        player.playSong("Senorita");
        player.playSong("Blank Space");
        player.playSong("Believer");
        player.playSong("Don't Start Now");
        player.playSong("Wake Me Up");
        player.playSong("Levitating");
        player.playSong("Circles");
        player.playSong("Moves Like Jagger");
        player.playSong("Wake Me Up");
        player.playSong("Wake Me Up");
        player.playSong("Wake Me Up");
        player.playSong("Wake Me Up");
        player.playSong("Levitating");
        player.playSong("Levitating");
        player.playSong("Levitating");

        LocalDate current = LocalDate.now();
        player.getTopSongs();
        System.out.println();
        System.out.println();
        player.getTopSongsByDate(current);
        System.out.println();
        System.out.println();
        player.nextDay();
        player.playSong("Don't Start Now");
        player.playSong("Don't Start Now");
        player.playSong("Don't Start Now");
        player.playSong("Blinding Lights");
        player.playSong("Blinding Lights");
        player.playSong("Believer");
        System.out.println();
        System.out.println();
        player.getTopSongsByDate(current.plusDays(1));
        System.out.println();
        System.out.println();
        player.getTopSongsByArtist("Linkin Park");


    }
}